// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8U9vS1qVQre-Y_KLOAhsxON35ekfSwCg',
    appId: '1:575622315387:web:c556a72ccc746133d0d1de',
    messagingSenderId: '575622315387',
    projectId: 'notspotify-321cc',
    authDomain: 'notspotify-321cc.firebaseapp.com',
    storageBucket: 'notspotify-321cc.firebasestorage.app',
    measurementId: 'G-L6LS92MEVV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7yTkYea5tcqBelxHpgcNNftMuvxzFwAw',
    appId: '1:575622315387:android:bd34424f9f9e13e4d0d1de',
    messagingSenderId: '575622315387',
    projectId: 'notspotify-321cc',
    storageBucket: 'notspotify-321cc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfMhQfS9Lp47H-5giwwV4mx6nezf_1V2k',
    appId: '1:575622315387:ios:0ace9e8556a6c1a0d0d1de',
    messagingSenderId: '575622315387',
    projectId: 'notspotify-321cc',
    storageBucket: 'notspotify-321cc.firebasestorage.app',
    iosBundleId: 'com.music.notspotify',
  );
}
